version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0 
    platform: linux/x86_64
    container_name: express_app_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_script.sql:/docker-entrypoint-initdb.d/db_script.sql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data: